// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicTestimonialContactForm } from "./plasmic/vermont_consumer_credit/PlasmicTestimonialContactForm";

function TestimonialContactForm_(props, ref) {
  // Use PlasmicTestimonialContactForm to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicTestimonialContactForm are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all TestimonialContactFormProps here, but feel free
  // to do whatever works for you.
  //return <PlasmicTestimonialContactForm root={{ ref }} {...props} />;
  return <PlasmicTestimonialContactForm>
   <iframe src="https://docs.google.com/forms/d/e/1FAIpQLScCrRjwjwK7rm4hkdkjJNsrP7VAFYc28kkfqs6bYYVHIy8e2Q/viewform?embedded=true" width="640" height="1328" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
  </PlasmicTestimonialContactForm>
}

const TestimonialContactForm = React.forwardRef(TestimonialContactForm_);

export default TestimonialContactForm;
