// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9W67x2Pynxr9eDxjdLuGCS
// Component: 6sPp355nJZ-s
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: mCxPr8fs96V/component
import Section from "../../Section"; // plasmic-import: TeEenYh07CLQ/component
import Faq from "../../Faq"; // plasmic-import: uvD0OplvXorD/component
import Footer from "../../Footer"; // plasmic-import: R265Q5ctgGy/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_vermont_consumer_credit.module.css"; // plasmic-import: 9W67x2Pynxr9eDxjdLuGCS/projectcss
import sty from "./PlasmicServices.module.css"; // plasmic-import: 6sPp355nJZ-s/css

export const PlasmicServices__VariantProps = new Array();

export const PlasmicServices__ArgProps = new Array();

function PlasmicServices__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <Section
            data-plasmic-name={"faqSection"}
            data-plasmic-override={overrides.faqSection}
            className={classNames("__wab_instance", sty.faqSection)}
            hasTitle={true}
            subtitle={
              "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur excepteur sint occaecat cupidatat."
            }
            title={"Services"}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__bE7Ne)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bepQ
                  )}
                >
                  {"Consumer"}
                </div>

                <Faq
                  className={classNames("__wab_instance", sty.faq__imjdE)}
                  slot={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3Zwqv
                        )}
                      >
                        {"Consumer Lending Education"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zE7Sg
                        )}
                      >
                        {"Post Bankruptcy Consumer Development"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3O6Em
                        )}
                      >
                        {"Life Changing Events and Finance"}
                      </div>
                    </React.Fragment>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8Uzwp
                    )}
                  >
                    {"Loan Workshops"}
                  </div>
                </Faq>

                <Faq
                  className={classNames("__wab_instance", sty.faq__rTo94)}
                  slot={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wgHa2
                        )}
                      >
                        {"Debt Management Strategies"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3O6Em
                        )}
                      >
                        {"Hardship Management and Planning"}
                      </div>
                    </React.Fragment>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yWIn
                    )}
                  >
                    {"Consumer Lending"}
                  </div>
                </Faq>

                <Faq
                  className={classNames("__wab_instance", sty.faq__ulr77)}
                  slot={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xm9Si
                        )}
                      >
                        {"Consumer Finance Education"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zE7Sg
                        )}
                      >
                        {"Realtor Consultation"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3O6Em
                        )}
                      >
                        {"Lender Consultation"}
                      </div>
                    </React.Fragment>
                  }
                >
                  {"Home Ownership"}
                </Faq>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__yQo9)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___81H7J
                  )}
                >
                  {"Corporate"}
                </div>

                <Faq
                  className={classNames("__wab_instance", sty.faq___80JaR)}
                  slot={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rheLc
                        )}
                      >
                        {"Emergency Finance Triage"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zE7Sg
                        )}
                      >
                        {"Financial Hardship Consulting"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3O6Em
                        )}
                      >
                        {"Professional Partnership Collaboration"}
                      </div>
                    </React.Fragment>
                  }
                >
                  {"Financial Services"}
                </Faq>

                <Faq
                  className={classNames("__wab_instance", sty.faq__tbiyY)}
                  slot={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5J5J1
                        )}
                      >
                        {"Employer Provided Benefit"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zE7Sg
                        )}
                      >
                        {"Consumer  Finance / Budgeting Education"}
                      </div>
                    </React.Fragment>
                  }
                >
                  {"Employee Workshops"}
                </Faq>

                <Faq
                  className={classNames("__wab_instance", sty.faq___0CRa)}
                  slot={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9SRZ
                        )}
                      >
                        {"Customer Referral Service (Loan Mitigation)"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zE7Sg
                        )}
                      >
                        {"Business Based Benefits for Consumer"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3O6Em
                        )}
                      >
                        {"Reduction in Lending Denials"}
                      </div>
                    </React.Fragment>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mFNrb
                    )}
                  >
                    {"Corporate Programs"}
                  </div>
                </Faq>
              </p.Stack>
            </p.Stack>

            {true ? (
              <p.Stack
                as={"div"}
                data-plasmic-name={"freeBox"}
                data-plasmic-override={overrides.freeBox}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ucw8O
                  )}
                >
                  {"Services"}
                </div>
              </p.Stack>
            ) : null}
          </Section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "header", "faqSection", "columns", "freeBox", "footer"],
  header: ["header"],
  faqSection: ["faqSection", "columns", "freeBox"],
  columns: ["columns"],
  freeBox: ["freeBox"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicServices__ArgProps,
      internalVariantPropNames: PlasmicServices__VariantProps
    });

    return PlasmicServices__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicServices";
  } else {
    func.displayName = `PlasmicServices.${nodeName}`;
  }
  return func;
}

export const PlasmicServices = Object.assign(
  // Top-level PlasmicServices renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    faqSection: makeNodeComponent("faqSection"),
    columns: makeNodeComponent("columns"),
    freeBox: makeNodeComponent("freeBox"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicServices
    internalVariantProps: PlasmicServices__VariantProps,
    internalArgProps: PlasmicServices__ArgProps
  }
);

export default PlasmicServices;
/* prettier-ignore-end */
