// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9W67x2Pynxr9eDxjdLuGCS
// Component: R265Q5ctgGy
import * as React from "react";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import IconLink from "../../IconLink"; // plasmic-import: EjLZdJRjcnq/component
import { useScreenVariants as useScreenVariantskcIfFDxm3XN2 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: KCIfFDxm3xN2/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_vermont_consumer_credit.module.css"; // plasmic-import: 9W67x2Pynxr9eDxjdLuGCS/projectcss
import sty from "./PlasmicFooter.module.css"; // plasmic-import: R265Q5ctgGy/css
import LogoIcon from "./icons/PlasmicIcon__Logo"; // plasmic-import: ajsvomRNRyt5/icon
import TwitterIconIcon from "./icons/PlasmicIcon__TwitterIcon"; // plasmic-import: VeC2uT8KWQf7/icon
import GithubIconIcon from "./icons/PlasmicIcon__GithubIcon"; // plasmic-import: BmWl-acuNUPO/icon
import FacebookIconIcon from "./icons/PlasmicIcon__FacebookIcon"; // plasmic-import: X4N2ic5_a6uK/icon

export const PlasmicFooter__VariantProps = new Array();

export const PlasmicFooter__ArgProps = new Array();

function PlasmicFooter__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantskcIfFDxm3XN2()
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__yi3Bm)} />

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__uVzoE)}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__jPby2)}
        >
          {true ? (
            <IconLink
              className={classNames("__wab_instance", sty.iconLink__nSLhU)}
              icon={
                <LogoIcon
                  className={classNames(projectcss.all, sty.svg__nNFb1)}
                  role={"img"}
                />
              }
            />
          ) : null}
          {true ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__y0HNl)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pwyRy
                )}
              >
                {"Vermont Consumer Credit Consulting"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lfDCj
                )}
              >
                {"802-922-6268"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__r2E5Z
                )}
              >
                {"PO Box 8156\nEssex Junction VT, 05451"}
              </div>

              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__dnXm
                )}
                component={Link}
                href={"/privacy-policy"}
                platform={"nextjs"}
              >
                {"Privacy Policy"}
              </p.PlasmicLink>

              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__jyIl7
                )}
                component={Link}
                href={"/lender-agreement"}
                platform={"nextjs"}
              >
                {"Lender Agreement"}
              </p.PlasmicLink>
            </p.Stack>
          ) : null}
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__o84Ev)}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___95TUp)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__j47BP
              )}
            >
              {"Consumer"}
            </div>

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__iatC
              )}
              component={Link}
              href={"#"}
              platform={"nextjs"}
            >
              {"Loan Workshops"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__wXx1M
              )}
              component={Link}
              href={"#"}
              platform={"nextjs"}
            >
              {"Consumer Lending"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__vwUdh
              )}
              component={Link}
              href={"#"}
              platform={"nextjs"}
            >
              {"Home Ownership"}
            </p.PlasmicLink>
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__lAoKd)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nqeFq
              )}
            >
              {"Corporate"}
            </div>

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__ckcgv
              )}
              component={Link}
              href={"#"}
              platform={"nextjs"}
            >
              {"Financial Services"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__zxIj0
              )}
              component={Link}
              href={"#"}
              platform={"nextjs"}
            >
              {"Employee Workshops"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__zaPwu
              )}
              component={Link}
              href={"#"}
              platform={"nextjs"}
            >
              {"Corporate Program"}
            </p.PlasmicLink>
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__yr1Hm)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qnsjn
              )}
            >
              {"Company"}
            </div>

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__xnc0L
              )}
              component={Link}
              href={"/"}
              platform={"nextjs"}
            >
              {"Home"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__nyrYw
              )}
              component={Link}
              href={"/about"}
              platform={"nextjs"}
            >
              {"About us"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__bHQz
              )}
              component={Link}
              href={"/about"}
              platform={"nextjs"}
            >
              {"Blog"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__c0DeW
              )}
              component={Link}
              href={"/testimonials"}
              platform={"nextjs"}
            >
              {"Testimonials"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__eB5G
              )}
              component={Link}
              href={"/contact"}
              platform={"nextjs"}
            >
              {"Request Appointment"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link___1M7V
              )}
              component={Link}
              href={"/contact"}
              platform={"nextjs"}
            >
              {"Contact"}
            </p.PlasmicLink>
          </p.Stack>
        </p.Stack>
      </p.Stack>

      <div className={classNames(projectcss.all, sty.freeBox___9BVlP)} />

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__sZx0Z)}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__pT9Mq)}
        >
          <p.PlasmicLink
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__rwOS
            )}
            component={Link}
            href={"/"}
            platform={"nextjs"}
          >
            {"Vermont Consumer Consulting"}
          </p.PlasmicLink>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__g19O6
            )}
          >
            {"All rights reserved."}
          </div>

          <p.PlasmicLink
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__ecLm4
            )}
            component={Link}
            href={"https://www.vtapi.co"}
            platform={"nextjs"}
            target={"_blank"}
          >
            {"vtapi.co"}
          </p.PlasmicLink>
        </p.Stack>

        {true ? (
          <p.Stack
            as={"div"}
            data-plasmic-name={"socialMediaLinks"}
            data-plasmic-override={overrides.socialMediaLinks}
            hasGap={true}
            className={classNames(projectcss.all, sty.socialMediaLinks)}
          >
            <IconLink
              className={classNames("__wab_instance", sty.iconLink___0TFo)}
              icon={
                <TwitterIconIcon
                  className={classNames(projectcss.all, sty.svg___1CfOu)}
                  role={"img"}
                />
              }
            />

            <IconLink
              className={classNames("__wab_instance", sty.iconLink__kiQpe)}
              icon={
                <GithubIconIcon
                  className={classNames(projectcss.all, sty.svg___3AkQm)}
                  role={"img"}
                />
              }
            />

            <IconLink
              className={classNames("__wab_instance", sty.iconLink__sDoFd)}
              icon={
                <FacebookIconIcon
                  className={classNames(projectcss.all, sty.svg___55Ypc)}
                  role={"img"}
                />
              }
            />
          </p.Stack>
        ) : null}
      </p.Stack>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "socialMediaLinks"],
  socialMediaLinks: ["socialMediaLinks"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooter__ArgProps,
      internalVariantPropNames: PlasmicFooter__VariantProps
    });

    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    socialMediaLinks: makeNodeComponent("socialMediaLinks"),
    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
