// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9W67x2Pynxr9eDxjdLuGCS
// Component: JV46E8AzoY
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: mCxPr8fs96V/component
import Section from "../../Section"; // plasmic-import: TeEenYh07CLQ/component
import Testimonial from "../../Testimonial"; // plasmic-import: UHonw5mKes0b/component
import Button from "../../Button"; // plasmic-import: jRx1E81mYCIy/component
import Footer from "../../Footer"; // plasmic-import: R265Q5ctgGy/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_vermont_consumer_credit.module.css"; // plasmic-import: 9W67x2Pynxr9eDxjdLuGCS/projectcss
import sty from "./PlasmicTestimonials.module.css"; // plasmic-import: JV46E8AzoY/css
import CycleIcon from "./icons/PlasmicIcon__Cycle"; // plasmic-import: F1nfD4e8NqAk/icon

export const PlasmicTestimonials__VariantProps = new Array();

export const PlasmicTestimonials__ArgProps = new Array();

export const defaultTestimonials__Args = {};

function PlasmicTestimonials__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultTestimonials__Args, props.args);
  const $props = args;
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{"Testimonials"}</title>
        <meta key="og:title" property="og:title" content={"Testimonials"} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <Section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames("__wab_instance", sty.section)}
            subtitle={"Basic page subtitle"}
            title={"Basic Page Title"}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__un7KO)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uRo
                )}
              >
                {"Testimonials"}
              </div>

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__myxGt)}
                person={"Ann Atkins"}
                quote={
                  "I had the opportunity to work side by side with John while in a therapeutic case management positon teaching life skills.  Establishing and maintaining credit was a huge part of the work done.  John is amazing, he has the ability to meet people where they are at, establish a trusting relationship, and walk with them on their journey to establishing credit, rapport and permanent housing! "
                }
                tagline={
                  true ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__udkxc
                      )}
                    >
                      {"CEO & Co-Founder @ Dropbox"}
                    </div>
                  ) : null
                }
              />

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__tptt)}
                person={"Timothy Carpenter"}
                quote={
                  "…I’ve worked with John and his clients multiple times. It’s always been a pleasure as John has his own banking and lending experience which makes it very easy to communicate what’s needed for the lenders standpoint. He’s shown a successful track record of negotiating bad debts."
                }
                tagline={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7M2Ol
                    )}
                  >
                    {"Senior Lending Manager / OCU "}
                  </div>
                }
              />

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__ejwyP)}
                person={"Timothy Carpenter"}
                quote={
                  "…I’ve worked with John and his clients multiple times. It’s always been a pleasure as John has his own banking and lending experience which makes it very easy to communicate what’s needed for the lenders standpoint. He’s shown a successful track record of negotiating bad debts."
                }
                tagline={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hqgD
                    )}
                  >
                    {"Senior Lending Manager / OCU "}
                  </div>
                }
              />

              <Testimonial
                className={classNames(
                  "__wab_instance",
                  sty.testimonial___4Gfj6
                )}
                person={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gCve3
                    )}
                  >
                    {"Anthony and Lee Bambara"}
                  </div>
                }
                quote={
                  "My wife and I were very intimidated at the prospect of buying a home. But John gave us the guidance to make the process simple. He explained what he was doing and the moves we were making, and never kept us in the dark. He answered our questions every step of the way, never made us feel ashamed for not being savvy to the world of lending, in fact he inspired confidence. His expertise made the process we were dreading so much a wholly painless experience. Cannot say enough kind things about the man, a well educated professional who I was happy to have in my corner!"
                }
                tagline={
                  true ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2FvOj
                      )}
                    >
                      {"Director of Finance @ ThirdThing"}
                    </div>
                  ) : null
                }
              />

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial___6LbZ)}
                person={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lsDAp
                    )}
                  >
                    {"Don Banks"}
                  </div>
                }
                quote={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__x0UZo
                    )}
                  >
                    {
                      "I was looking to find out what my credit score was and John Goffe was instrumental in helping me. John couldn't even find me in the system, it's like i didn't exist. He took the time to understand who I was and where I had come from, with no judgemental passed. He explained to me what had to be done, got me started and I went back to him two months later to check in, to both of our surprise, i finally had a credit score, and it was amazing. For the first time I felt like existed and i was somebody. I wholeheartedly recommend John Goffe to everyone we know, if they need any type of consult. He's very genuine and honest."
                    }
                  </div>
                }
                tagline={
                  true ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__khk2D
                      )}
                    >
                      {"Director of Finance @ ThirdThing"}
                    </div>
                  ) : null
                }
              />

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__xlZy7)}
                person={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mHd2Y
                    )}
                  >
                    {"Trista Baker "}
                  </div>
                }
                quote={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ltSmU
                    )}
                  >
                    {
                      "I went to  credit union and met with John Goffe, to go over my credit. I was looking to purchase a home, but knew my credit needed to be fixed. John sat down with me and went over everyrhing that appeared on my credit report. He took the time to explain what was good on there and what needed to be fixed. When he finished, he immediately went to work making phone calls and got the negative reports to settle for lower amounts. John also made the checks out and sent them to the appropriate people. He made fixing my credit stress free and helped me achieve one of my biggest goals, to be able to have great credit and purchase a home. John was an important part to help me understand about credit utilization, credit spending, maintaining and keeping a good credit score. I appreciated the time he took to help me and not make me feel like I was failure. He's sincere, genuine and honest and takes the time to explain things. I wouldn't be where I am today, if he didn't help me take that first step."
                    }
                  </div>
                }
                tagline={
                  true ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wc9F9
                      )}
                    >
                      {"Director of Finance @ ThirdThing"}
                    </div>
                  ) : null
                }
              />

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__isjLq)}
                person={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jNNo7
                    )}
                  >
                    {"Linda Siple"}
                  </div>
                }
                quote={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__foLhg
                    )}
                  >
                    {
                      '"I was in foreclosure when I first met John. My credit was poor and I was in a financial bind. After my husband and I worked with John we were able to pay off our mortgage, help rebuild our credit history, and now have a safe vehicle for us to get to our appointments. John was phenomenal at helping me understand my credit and how things work. He has really helped to instill alot of great knowledge on how to handle my finances and great budgeting tactics that I utilize daily. He has really helped me turn our financial future in a more positive direction and I am very grateful to be able to pass these habits onto my grandkids."'
                    }
                  </div>
                }
                tagline={
                  true ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jdlMt
                      )}
                    >
                      {"Director of Finance @ ThirdThing"}
                    </div>
                  ) : null
                }
              />

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__hSbmO)}
                person={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uvcgA
                    )}
                  >
                    {"Tinika Lau "}
                  </div>
                }
                quote={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ykmpj
                    )}
                  >
                    {
                      'I was a single mom with barely any credit. John was a great resource and a great help when I needed to buy my home. He taught me how to read a credit report, he walked me through the classes needed for the first time home buyers financing, and has been a fountain of knowledge that has helped me get to where I am today. I now own a house and have a new reliable vehicle that is safe for for family. I am also able to qualify for things I could not before due to my increased credit worthiness."'
                    }
                  </div>
                }
                tagline={
                  true ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5MMqO
                      )}
                    >
                      {"Director of Finance @ ThirdThing"}
                    </div>
                  ) : null
                }
              />

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__juCBc)}
                person={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tl2Oj
                    )}
                  >
                    {"Krystal Shattuck"}
                  </div>
                }
                quote={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5Y3Em
                    )}
                  >
                    {
                      "Where do I begin. When I first met Jon he was working at Opportunities. I was set up with him because I had good credit but my income to debt ratio was terrible. I couldn't get a loan for a car or a mortgage for a house. Well I walked into his office and we hit it right off. He was very friendly, knowledgeable and funny. He made me feel like he cared and he does. He helped me get myself straightened out and now I am good to go."
                    }
                  </div>
                }
                tagline={
                  true ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fibVf
                      )}
                    >
                      {"Director of Finance @ ThirdThing"}
                    </div>
                  ) : null
                }
              />

              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__uF8Xj)}
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__gK8Ah)}
                    color={"outlineBlue"}
                    link={"/contact"}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__aAaTf
                      )}
                    >
                      {"Request Infomration Today"}
                    </div>
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__ietiQ)}
                    color={"blue"}
                    endIcon={
                      <CycleIcon
                        data-plasmic-name={"svg"}
                        data-plasmic-override={overrides.svg}
                        className={classNames(projectcss.all, sty.svg)}
                        role={"img"}
                      />
                    }
                    link={"/submit-testimonial"}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tVbu
                      )}
                    >
                      {"Submit a Testimonial"}
                    </div>
                  </Button>
                </p.Stack>
              ) : null}
            </p.Stack>
          </Section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "header", "section", "svg", "footer"],
  header: ["header"],
  section: ["section", "svg"],
  svg: ["svg"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTestimonials__ArgProps,
      internalVariantPropNames: PlasmicTestimonials__VariantProps
    });

    return PlasmicTestimonials__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestimonials";
  } else {
    func.displayName = `PlasmicTestimonials.${nodeName}`;
  }
  return func;
}

export const PlasmicTestimonials = Object.assign(
  // Top-level PlasmicTestimonials renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    section: makeNodeComponent("section"),
    svg: makeNodeComponent("svg"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicTestimonials
    internalVariantProps: PlasmicTestimonials__VariantProps,
    internalArgProps: PlasmicTestimonials__ArgProps
  }
);

export default PlasmicTestimonials;
/* prettier-ignore-end */
